import { NvidiaNimEndpointProfile } from './types';

export const NVIDIA_NIM_PRESETS: NvidiaNimEndpointProfile[] = [
  {
    id: 'preset_nvidia_deepseek_v4',
    displayName: 'NVIDIA Build — DeepSeek V4 Flash',
    source: 'nvidia_build',
    capability: 'chat',
    modelId: 'deepseek-ai/deepseek-v4-flash',
    baseUrl: 'https://integrate.api.nvidia.com',
    endpointPath: '/v1/chat/completions',
    httpMethod: 'POST',
    authStrategy: 'nvidia_bearer',
    requestFormat: 'openai_chat',
    responseFormat: 'openai_sse',
    supportsStreaming: true,
    supportsModelDiscovery: true,
    availabilityLabel: 'Free Endpoint',
    configurableParameters: [
      { key: 'temperature', label: 'Temperature', type: 'number', required: false, defaultValue: 0.7, minimum: 0, maximum: 2 },
      { key: 'top_p', label: 'Top P', type: 'number', required: false, defaultValue: 1.0, minimum: 0, maximum: 1 },
      { key: 'reasoning_budget', label: 'Reasoning Budget', type: 'number', required: false, defaultValue: 1024, minimum: 0, maximum: 8192 },
    ],
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_nvidia_qwen_3_5',
    displayName: 'NVIDIA Build — Qwen 3.5 122B Instruct',
    source: 'nvidia_build',
    capability: 'chat',
    modelId: 'qwen/qwen3.5-122b-a10b',
    baseUrl: 'https://integrate.api.nvidia.com',
    endpointPath: '/v1/chat/completions',
    httpMethod: 'POST',
    authStrategy: 'nvidia_bearer',
    requestFormat: 'openai_chat',
    responseFormat: 'openai_sse',
    supportsStreaming: true,
    supportsModelDiscovery: true,
    availabilityLabel: 'Free Endpoint',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_nvidia_llama_3_3',
    displayName: 'NVIDIA Build — Llama 3.3 70B Instruct',
    source: 'nvidia_build',
    capability: 'chat',
    modelId: 'meta/llama-3.3-70b-instruct',
    baseUrl: 'https://integrate.api.nvidia.com',
    endpointPath: '/v1/chat/completions',
    httpMethod: 'POST',
    authStrategy: 'nvidia_bearer',
    requestFormat: 'openai_chat',
    responseFormat: 'openai_sse',
    supportsStreaming: true,
    supportsModelDiscovery: true,
    availabilityLabel: 'Free Endpoint',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_nvidia_responses',
    displayName: 'NVIDIA Build — OpenAI Responses API',
    source: 'nvidia_build',
    capability: 'responses',
    modelId: 'nvidia/llama-3.1-nemotron-70b-instruct',
    baseUrl: 'https://integrate.api.nvidia.com',
    endpointPath: '/v1/responses',
    httpMethod: 'POST',
    authStrategy: 'nvidia_bearer',
    requestFormat: 'openai_responses',
    responseFormat: 'openai_json',
    supportsStreaming: false,
    supportsModelDiscovery: false,
    availabilityLabel: 'Free Endpoint',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_self_hosted_nim_chat',
    displayName: 'Self-Hosted NIM — Local Chat (v1/chat/completions)',
    source: 'self_hosted_nim',
    capability: 'chat',
    modelId: 'meta/llama3-8b-instruct',
    baseUrl: 'http://localhost:8000',
    endpointPath: '/v1/chat/completions',
    httpMethod: 'POST',
    authStrategy: 'none',
    requestFormat: 'openai_chat',
    responseFormat: 'openai_sse',
    supportsStreaming: true,
    supportsModelDiscovery: true,
    isSelfHosted: true,
    allowLocalhost: true,
    availabilityLabel: 'Self-Hosted',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_self_hosted_nim_embeddings',
    displayName: 'Self-Hosted NIM — Embeddings (v1/embeddings)',
    source: 'self_hosted_nim',
    capability: 'embeddings',
    modelId: 'nvidia/nv-embed-v1',
    baseUrl: 'http://localhost:8000',
    endpointPath: '/v1/embeddings',
    httpMethod: 'POST',
    authStrategy: 'none',
    requestFormat: 'nvidia_embeddings',
    responseFormat: 'json',
    supportsStreaming: false,
    supportsModelDiscovery: false,
    isSelfHosted: true,
    allowLocalhost: true,
    availabilityLabel: 'Self-Hosted',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_self_hosted_nim_rerank',
    displayName: 'Self-Hosted NIM — Reranking (v1/ranking)',
    source: 'self_hosted_nim',
    capability: 'reranking',
    modelId: 'nvidia/llama-nemotron-rerank-1b-v2',
    baseUrl: 'http://localhost:8000',
    endpointPath: '/v1/ranking',
    httpMethod: 'POST',
    authStrategy: 'none',
    requestFormat: 'nvidia_ranking',
    responseFormat: 'json',
    supportsStreaming: false,
    supportsModelDiscovery: false,
    isSelfHosted: true,
    allowLocalhost: true,
    availabilityLabel: 'Self-Hosted',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
  {
    id: 'preset_nvcf_invocation',
    displayName: 'NVCF Invocation — Custom NVIDIA API',
    source: 'nvcf_invocation',
    capability: 'chat',
    modelId: 'custom-nvcf-model',
    baseUrl: 'https://api.nvcf.nvidia.com',
    endpointPath: '/v2/nvcf/pexec/functions/custom-function-id',
    httpMethod: 'POST',
    authStrategy: 'bearer',
    requestFormat: 'openai_chat',
    responseFormat: 'openai_json',
    supportsStreaming: false,
    supportsModelDiscovery: false,
    availabilityLabel: 'Partner Endpoint',
    createdAt: 1700000000000,
    updatedAt: 1700000000000,
  },
];
